-- Adaca Analytics — initial schema (D1 / SQLite).
--
-- Conventions (config tables): `id` is a 10-char nanoid text generated by the
-- app, followed by `created_at` / `updated_at` (ISO-8601 UTC, maintained by a
-- trigger). Plural table names. Soft delete via `deleted_at` where a record
-- can be referenced elsewhere.
--
-- `rollups` is the one fact table and deliberately has NO surrogate id: its
-- natural key (site, report, date, key1, key2) is the only way it is ever
-- addressed, and a WITHOUT ROWID composite key is both smaller and faster
-- for the range scans every widget runs.

CREATE TABLE sites (
  id                 TEXT PRIMARY KEY,
  created_at         TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  updated_at         TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  name               TEXT NOT NULL,
  -- Numeric GA4 property id (the part after "properties/"). NULL for a
  -- BigQuery-only site (e.g. the public sample dataset), which then has no
  -- realtime view.
  ga_property_id     TEXT,
  timezone           TEXT NOT NULL DEFAULT 'UTC',
  currency           TEXT NOT NULL DEFAULT 'USD',
  -- Where daily rollups come from. Realtime is always GA4 (needs ga_property_id).
  primary_source     TEXT NOT NULL DEFAULT 'ga4' CHECK (primary_source IN ('ga4', 'bigquery')),
  -- BigQuery: the project that RUNS query jobs (billed) and the export
  -- dataset, fully qualified as `project.dataset` (a bare name means the
  -- jobs project).
  bq_project_id      TEXT,
  bq_dataset         TEXT,
  -- Default backfill window when a site is created / re-backfilled.
  backfill_days      INTEGER NOT NULL DEFAULT 90,
  last_ingested_date TEXT,
  position           INTEGER NOT NULL DEFAULT 0,
  deleted_at         TEXT,
  CHECK (ga_property_id IS NOT NULL OR bq_dataset IS NOT NULL)
);

CREATE TRIGGER touch_sites AFTER UPDATE ON sites
BEGIN
  UPDATE sites SET updated_at = strftime('%Y-%m-%dT%H:%M:%fZ', 'now') WHERE id = NEW.id;
END;

CREATE TABLE dashboards (
  id           TEXT PRIMARY KEY,
  created_at   TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  updated_at   TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  slug         TEXT NOT NULL UNIQUE,
  name         TEXT NOT NULL,
  kind         TEXT NOT NULL DEFAULT 'custom' CHECK (kind IN ('default', 'custom')),
  -- Which built-in template seeded this dashboard (and what "Reset" restores).
  template_key TEXT,
  position     INTEGER NOT NULL DEFAULT 0,
  -- JSON: WidgetInstance[] — read whole, never queried column-wise.
  layout       TEXT NOT NULL DEFAULT '[]',
  deleted_at   TEXT
);

CREATE TRIGGER touch_dashboards AFTER UPDATE ON dashboards
BEGIN
  UPDATE dashboards SET updated_at = strftime('%Y-%m-%dT%H:%M:%fZ', 'now') WHERE id = NEW.id;
END;

-- One row per (site, report family, day, dimension value[s]). Every family
-- shares the same metric columns so the query layer is one SQL shape.
CREATE TABLE rollups (
  site_id            TEXT NOT NULL REFERENCES sites(id) ON DELETE CASCADE,
  report             TEXT NOT NULL,
  date               TEXT NOT NULL,           -- YYYY-MM-DD in the property's timezone
  key1               TEXT NOT NULL DEFAULT '',
  key2               TEXT NOT NULL DEFAULT '',
  users              INTEGER NOT NULL DEFAULT 0,
  new_users          INTEGER NOT NULL DEFAULT 0,
  sessions           INTEGER NOT NULL DEFAULT 0,
  engaged_sessions   INTEGER NOT NULL DEFAULT 0,
  pageviews          INTEGER NOT NULL DEFAULT 0,
  engagement_seconds REAL    NOT NULL DEFAULT 0,
  key_events         INTEGER NOT NULL DEFAULT 0,
  event_count        INTEGER NOT NULL DEFAULT 0,
  PRIMARY KEY (site_id, report, date, key1, key2)
) WITHOUT ROWID;

CREATE TABLE ingest_runs (
  id           TEXT PRIMARY KEY,
  created_at   TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  updated_at   TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  site_id      TEXT NOT NULL REFERENCES sites(id) ON DELETE CASCADE,
  kind         TEXT NOT NULL CHECK (kind IN ('backfill', 'daily', 'manual')),
  from_date    TEXT NOT NULL,
  to_date      TEXT NOT NULL,
  -- JSON progress cursor: { "report": <index>, "chunk": "YYYY-MM-DD", "offset": <rows> }
  cursor       TEXT NOT NULL DEFAULT '{}',
  status       TEXT NOT NULL DEFAULT 'queued' CHECK (status IN ('queued', 'running', 'done', 'failed')),
  rows_written INTEGER NOT NULL DEFAULT 0,
  units        INTEGER NOT NULL DEFAULT 0,
  error        TEXT,
  started_at   TEXT,
  finished_at  TEXT
);

CREATE INDEX ingest_runs_site_created ON ingest_runs (site_id, created_at);
CREATE INDEX ingest_runs_status ON ingest_runs (status);

CREATE TRIGGER touch_ingest_runs AFTER UPDATE ON ingest_runs
BEGIN
  UPDATE ingest_runs SET updated_at = strftime('%Y-%m-%dT%H:%M:%fZ', 'now') WHERE id = NEW.id;
END;

CREATE TABLE settings (
  id         TEXT PRIMARY KEY,
  created_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  updated_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  key        TEXT NOT NULL UNIQUE,
  value      TEXT NOT NULL DEFAULT 'null'   -- JSON
);

CREATE TRIGGER touch_settings AFTER UPDATE ON settings
BEGIN
  UPDATE settings SET updated_at = strftime('%Y-%m-%dT%H:%M:%fZ', 'now') WHERE id = NEW.id;
END;
